version: '2'

services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.13
    ports:
      - 80:80
      - 443:443
      - 5050:5050
    volumes:
      - ./conf/vhosts:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
      - ./www/:/var/www/
    networks:
      - php-server  
  php5:
    container_name: php5
    restart: always
    image: php:5.6-fpm
    ports: 
      - 9000:9000
    networks:
      - php-server
networks:
  php-server:
    driver: bridge